CREATE TABLE IF NOT EXISTS PROFILES (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
