CREATE TABLE IF NOT EXISTS REPLIES (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    message TEXT NOT NULL,
    creation_date DATETIME NOT NULL,
    solution BOOLEAN NOT NULL,
    user_id INT NOT NULL,
    topic_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (topic_id) REFERENCES TOPICS(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
